import assert from "node:assert/strict";
import test from "node:test";
import { mkdir, mkdtemp, readdir, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { spawnSync } from "node:child_process";
import { DatabaseSync } from "node:sqlite";
import { run } from "../src/io.js";
import { RepositoryEngine } from "../src/repository-engine.js";

function commitAll(root:string):void{spawnSync("git",["config","user.email","rke-test@example.invalid"],{cwd:root});spawnSync("git",["config","user.name","RKE Test"],{cwd:root});spawnSync("git",["add","-A"],{cwd:root});spawnSync("git",["commit","-m","fixture"],{cwd:root});}

test("command runner accepts bounded repository-scale Git output",()=>{const root=process.cwd();const result=run(process.execPath,["-e","process.stdout.write('x'.repeat(2_000_000))"],root);assert.equal(result.code,0,result.stderr);assert.equal(result.stdout.length,2_000_000);});

test("hot freshness verifies Git state without hashing tracked files",async()=>{const root=await mkdtemp(join(tmpdir(),"rke-fresh-"));spawnSync("git",["init"],{cwd:root});await writeFile(join(root,"main.ts"),"export const value = 1;\n");commitAll(root);const engine=await RepositoryEngine.open(root);const cold=await engine.ensureFresh();const hot=await engine.ensureFresh();assert.equal(cold.parsed,1);assert.equal(hot.parsed,0);assert.equal(hot.hashedFiles,0);assert.equal(hot.reused,1);assert.equal(engine.processMetrics().gitProcessCount,3);assert.equal(engine.processMetrics().refreshCount,1);engine.close();});
test("changed files update independently",async()=>{const root=await mkdtemp(join(tmpdir(),"rke-change-"));spawnSync("git",["init"],{cwd:root});await writeFile(join(root,"a.ts"),"export function before() {}\n");await writeFile(join(root,"b.ts"),"export function stable() {}\n");commitAll(root);const engine=await RepositoryEngine.open(root);await engine.ensureFresh();await writeFile(join(root,"a.ts"),"export function after() {}\n");const refreshed=await engine.ensureFresh();assert.equal(refreshed.parsed,1);assert.equal(refreshed.reused,1);assert.match(JSON.stringify(await engine.fileApi("a.ts")),/after/);engine.close();});
test("stable dirty files do not rebuild and another same-size edit is detected",async()=>{const root=await mkdtemp(join(tmpdir(),"rke-dirty-hot-"));spawnSync("git",["init"],{cwd:root});const path=join(root,"main.ts");await writeFile(path,"export const value = 1;\n");commitAll(root);const engine=await RepositoryEngine.open(root);await engine.ensureFresh();await writeFile(path,"export const value = 2;\n");assert.equal((await engine.ensureFresh()).parsed,1);const secondHash=((await engine.fileApi("main.ts")).file as Record<string,unknown>).content_hash;const before=engine.processMetrics();for(let index=0;index<5;index++)assert.equal((await engine.ensureFresh()).parsed,0);assert.equal(engine.processMetrics().refreshCount,before.refreshCount);assert.equal(engine.processMetrics().gitProcessCount-before.gitProcessCount,5);await writeFile(path,"export const value = 3;\n");assert.equal((await engine.ensureFresh()).parsed,1);assert.notEqual(((await engine.fileApi("main.ts")).file as Record<string,unknown>).content_hash,secondHash);engine.close();});
test("explicit content verification hashes clean tracked files without reparsing",async()=>{const root=await mkdtemp(join(tmpdir(),"rke-fingerprint-"));spawnSync("git",["init"],{cwd:root});await writeFile(join(root,"main.ts"),"export const value = 1;\n");commitAll(root);const engine=await RepositoryEngine.open(root);const cold=await engine.ensureFresh();const warm=await engine.ensureFresh(true);assert.equal(cold.parsed,1);assert.equal(cold.hashedFiles,1);assert.equal(warm.parsed,0);assert.equal(warm.hashedFiles,1);assert.equal(warm.reusedFiles,1);assert.equal(engine.processMetrics().gitProcessCount,4);engine.close();});
test("corrupt SQLite state is quarantined and rebuilt",async()=>{const root=await mkdtemp(join(tmpdir(),"rke-corrupt-"));spawnSync("git",["init"],{cwd:root});const cache=join(root,".engineering-workflow","cache");await mkdir(cache,{recursive:true});await writeFile(join(cache,"rke.sqlite"),"not a sqlite database");await writeFile(join(root,"main.ts"),"export const recovered = true;\n");const engine=await RepositoryEngine.open(root);const fresh=await engine.ensureFresh();assert.equal(fresh.parsed,1);engine.close();assert.ok((await readdir(cache)).some(path=>path.startsWith("rke.sqlite.corrupt-")));});
test("older disposable schemas migrate in place",async()=>{const root=await mkdtemp(join(tmpdir(),"rke-migration-"));spawnSync("git",["init"],{cwd:root});const cache=join(root,".engineering-workflow","cache");await mkdir(cache,{recursive:true});const database=new DatabaseSync(join(cache,"rke.sqlite"));database.exec("CREATE TABLE meta (key TEXT PRIMARY KEY, value TEXT NOT NULL); INSERT INTO meta VALUES ('schema_version','2'); CREATE TABLE files (id INTEGER PRIMARY KEY);");database.close();await writeFile(join(root,"main.ts"),"export const migrated = true;\n");const engine=await RepositoryEngine.open(root);assert.equal((await engine.ensureFresh()).parsed,1);const api=await engine.fileApi("main.ts");assert.equal(api.found,true);assert.equal((api.file as Record<string,unknown>).status,"parsed");engine.close();});
test("WAL mode supports concurrent readers without materialising a shared graph",async()=>{const root=await mkdtemp(join(tmpdir(),"rke-readers-"));spawnSync("git",["init"],{cwd:root});await writeFile(join(root,"main.ts"),"export function concurrentReader() { return true; }\n");const first=await RepositoryEngine.open(root);await first.ensureFresh();const second=await RepositoryEngine.open(root);const [left,right]=await Promise.all([first.search("concurrent reader",5),second.fileApi("main.ts")]);assert.ok(left.length>0);assert.equal(right.found,true);first.close();second.close();});
test("change impact refreshes once before tracing current SQLite state",async()=>{const root=await mkdtemp(join(tmpdir(),"rke-impact-refresh-"));spawnSync("git",["init"],{cwd:root});const path=join(root,"main.ts");await writeFile(path,"export function first() { return second(); }\nexport function second() { return true; }\n");commitAll(root);const engine=await RepositoryEngine.open(root);await engine.ensureFresh();await writeFile(path,"export function first() { return second(); }\nexport function second() { return true; }\nexport function third() { return first(); }\n");const before=engine.processMetrics().refreshCount;const impact=await engine.changeImpact(["main.ts"]);assert.ok((impact.symbols as string[]).length>=3);assert.equal(engine.processMetrics().refreshCount-before,1);engine.close();});
test("concurrent public queries coalesce one dirty freshness pass",async()=>{const root=await mkdtemp(join(tmpdir(),"rke-coalesced-refresh-"));spawnSync("git",["init"],{cwd:root});const path=join(root,"main.ts");await writeFile(path,"export function coalesced() { return true; }\n");commitAll(root);const engine=await RepositoryEngine.open(root);await engine.ensureFresh();await writeFile(path,"export function coalesced() { return false; }\n");const before=engine.processMetrics().refreshCount;await Promise.all([engine.search("coalesced",5),engine.fileApi("main.ts"),engine.repositoryMap()]);assert.equal(engine.processMetrics().refreshCount-before,1);engine.close();});
