import assert from "node:assert/strict";
import test from "node:test";
import { mkdir, mkdtemp, readdir, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { spawnSync } from "node:child_process";
import { DatabaseSync } from "node:sqlite";
import { RepositoryEngine } from "../src/repository-engine.js";

test("warm freshness does not rebuild unchanged files",async()=>{const root=await mkdtemp(join(tmpdir(),"rke-fresh-"));spawnSync("git",["init"],{cwd:root});await writeFile(join(root,"main.ts"),"export const value = 1;\n");const engine=await RepositoryEngine.open(root);const cold=await engine.ensureFresh();const warm=await engine.ensureFresh();assert.equal(cold.parsed,1);assert.equal(warm.parsed,0);assert.equal(warm.reused,1);engine.close();});
test("changed files update independently",async()=>{const root=await mkdtemp(join(tmpdir(),"rke-change-"));spawnSync("git",["init"],{cwd:root});await writeFile(join(root,"a.ts"),"export function before() {}\n");await writeFile(join(root,"b.ts"),"export function stable() {}\n");const engine=await RepositoryEngine.open(root);await engine.ensureFresh();await new Promise(resolve=>setTimeout(resolve,20));await writeFile(join(root,"a.ts"),"export function after() {}\n");const refreshed=await engine.ensureFresh();assert.equal(refreshed.parsed,1);assert.equal(refreshed.reused,1);assert.match(JSON.stringify(await engine.fileApi("a.ts")),/after/);engine.close();});
test("stable file metadata reuses content identity without hashing",async()=>{const root=await mkdtemp(join(tmpdir(),"rke-fingerprint-"));spawnSync("git",["init"],{cwd:root});await writeFile(join(root,"main.ts"),"export const value = 1;\n");const engine=await RepositoryEngine.open(root);const cold=await engine.ensureFresh();const warm=await engine.ensureFresh();assert.equal(cold.parsed,1);assert.equal(cold.hashedFiles,1);assert.equal(warm.parsed,0);assert.equal(warm.hashedFiles,0);assert.equal(warm.reusedFiles,1);engine.close();});
test("corrupt SQLite state is quarantined and rebuilt",async()=>{const root=await mkdtemp(join(tmpdir(),"rke-corrupt-"));spawnSync("git",["init"],{cwd:root});const cache=join(root,".engineering-workflow","cache");await mkdir(cache,{recursive:true});await writeFile(join(cache,"rke.sqlite"),"not a sqlite database");await writeFile(join(root,"main.ts"),"export const recovered = true;\n");const engine=await RepositoryEngine.open(root);const fresh=await engine.ensureFresh();assert.equal(fresh.parsed,1);engine.close();assert.ok((await readdir(cache)).some(path=>path.startsWith("rke.sqlite.corrupt-")));});
test("older disposable schemas migrate in place",async()=>{const root=await mkdtemp(join(tmpdir(),"rke-migration-"));spawnSync("git",["init"],{cwd:root});const cache=join(root,".engineering-workflow","cache");await mkdir(cache,{recursive:true});const database=new DatabaseSync(join(cache,"rke.sqlite"));database.exec("CREATE TABLE meta (key TEXT PRIMARY KEY, value TEXT NOT NULL); INSERT INTO meta VALUES ('schema_version','2'); CREATE TABLE files (id INTEGER PRIMARY KEY);");database.close();await writeFile(join(root,"main.ts"),"export const migrated = true;\n");const engine=await RepositoryEngine.open(root);assert.equal((await engine.ensureFresh()).parsed,1);const api=await engine.fileApi("main.ts");assert.equal(api.found,true);assert.equal((api.file as Record<string,unknown>).status,"parsed");engine.close();});
test("WAL mode supports concurrent readers without materialising a shared graph",async()=>{const root=await mkdtemp(join(tmpdir(),"rke-readers-"));spawnSync("git",["init"],{cwd:root});await writeFile(join(root,"main.ts"),"export function concurrentReader() { return true; }\n");const first=await RepositoryEngine.open(root);await first.ensureFresh();const second=await RepositoryEngine.open(root);const [left,right]=await Promise.all([first.search("concurrent reader",5),second.fileApi("main.ts")]);assert.ok(left.length>0);assert.equal(right.found,true);first.close();second.close();});
