import assert from "node:assert/strict";
import test from "node:test";
import { cp, mkdir, mkdtemp, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { spawnSync } from "node:child_process";
import { readFile } from "node:fs/promises";

import { invokeOperation, OPERATIONS } from "../src/operations.js";
import { CLI_ROUTES } from "../src/cli-routes.js";
import { VERSION } from "../src/version.js";

test("publishes the complete 43-operation surface",()=>{assert.equal(OPERATIONS.length,43);assert.equal(new Set(OPERATIONS.map(v=>v.name)).size,43);assert.ok(OPERATIONS.every(v=>v.inputSchema.type==="object"));});
test("CLI routes and MCP operation discovery cover the same registry",()=>{assert.deepEqual([...new Set(Object.values(CLI_ROUTES).map(route=>route.operation))].sort(),OPERATIONS.map(operation=>operation.name).sort());});
test("matches the frozen public-operation inventory",async()=>{const fixture=JSON.parse(await readFile(join(process.cwd(),"tests/fixtures/public-operations.json"),"utf8")) as {operations:string[]};assert.deepEqual(OPERATIONS.map(value=>value.name),fixture.operations);});
test("runtime and npm package versions are identical",async()=>{const packageJson=JSON.parse(await readFile(join(process.cwd(),"package.json"),"utf8")) as {version:string};assert.equal(VERSION,packageJson.version);});
test("workflow lifecycle preserves gates and evidence",async()=>{const root=await mkdtemp(join(tmpdir(),"rke-workflow-"));spawnSync("git",["init"],{cwd:root});let result=await invokeOperation(root,"workflow_activate",{});assert.equal(result.exitCode,0);result=await invokeOperation(root,"workflow_gate_add",{gates:["implementation-validation"]});assert.deepEqual((result.payload.state as Record<string,unknown>).outstanding_gates,["implementation-validation"]);result=await invokeOperation(root,"workflow_close",{});assert.equal(result.exitCode,3);result=await invokeOperation(root,"workflow_gate_resolve",{gate:"implementation-validation",evidence:"tests pass"});assert.equal(result.exitCode,0);result=await invokeOperation(root,"workflow_close",{});assert.equal(result.payload.result,"closed");});
test("design re-entry reopens acceptance after convergence reset",async()=>{const root=await mkdtemp(join(tmpdir(),"rke-convergence-"));spawnSync("git",["init"],{cwd:root});await invokeOperation(root,"workflow_activate",{});let result=await invokeOperation(root,"workflow_journey_enter",{journey:"design"});assert.ok(((result.payload.state as Record<string,unknown>).outstanding_gates as string[]).includes("acceptance-defined"));await invokeOperation(root,"workflow_gate_resolve",{gate:"acceptance-defined",evidence:"initial contract"});result=await invokeOperation(root,"workflow_journey_enter",{journey:"design"});assert.ok(((result.payload.state as Record<string,unknown>).outstanding_gates as string[]).includes("acceptance-defined"));});
test("rejects unknown and extra operation arguments",async()=>{const root=await mkdtemp(join(tmpdir(),"rke-schema-"));await assert.rejects(()=>invokeOperation(root,"workflow_resume",{unexpected:true}),/unsupported properties/);await assert.rejects(()=>invokeOperation(root,"unknown",{}),/Unknown operation/);});
test("malformed workflow state is reported rather than replaced",async()=>{const root=await mkdtemp(join(tmpdir(),"rke-invalid-state-"));await mkdir(join(root,".engineering-workflow"),{recursive:true});await writeFile(join(root,".engineering-workflow","state.json"),JSON.stringify({schema_version:99,revision:-1,status:"active",primary_phase:"invent",active_capabilities:[],outstanding_gates:[],task_tracking:{mode:"none",task_ref:null},continuity:{checkpoint:null}}));const result=await invokeOperation(root,"workflow_resume",{});assert.equal(result.exitCode,2);assert.equal(result.payload.result,"invalid-state");});
test("concurrent workflow mutations never silently lose a successful write",async()=>{const root=await mkdtemp(join(tmpdir(),"rke-concurrent-state-"));spawnSync("git",["init"],{cwd:root});await invokeOperation(root,"workflow_activate",{});const settled=await Promise.allSettled([invokeOperation(root,"workflow_gate_add",{gates:["alpha"]}),invokeOperation(root,"workflow_gate_add",{gates:["beta"]})]);const successful=settled.filter(item=>item.status==="fulfilled");assert.ok(successful.length>=1);const resumed=await invokeOperation(root,"workflow_resume",{});const gates=(resumed.payload.state as Record<string,unknown>).outstanding_gates as string[];for(const item of successful){const added=(item as PromiseFulfilledResult<Awaited<ReturnType<typeof invokeOperation>>>).value.payload.added as string[];for(const gate of added)assert.ok(gates.includes(gate));}assert.ok(successful.length===2||settled.some(item=>item.status==="rejected"));});
test("indexes and retrieves TypeScript in-process",async()=>{const root=await mkdtemp(join(tmpdir(),"rke-repo-"));spawnSync("git",["init"],{cwd:root});await writeFile(join(root,"service.ts"),"export function calculateInvoice(total: number) { return total * 2; }\n");const api=await invokeOperation(root,"repo_file_api",{path:"service.ts"});assert.equal(api.exitCode,0);assert.match(JSON.stringify(api.payload),/calculateInvoice/);const search=await invokeOperation(root,"repo_find_context",{query:"calculate invoice",limit:5});assert.ok((search.payload.matches as unknown[]).length>0);});
test("knowledge receipts hash the exact registered source set without secret-scanner-shaped keys",async(t)=>{const root=await mkdtemp(join(tmpdir(),"rke-knowledge-"));spawnSync("git",["init"],{cwd:root});await mkdir(join(root,"docs"),{recursive:true});await mkdir(join(root,"src"),{recursive:true});await writeFile(join(root,"docs","architecture.md"),"# Architecture\n");await writeFile(join(root,"src","auth.ts"),"export const authorised = true;\n");await writeFile(join(root,"src","engine.ts"),"export const engine = true;\n");let result=await invokeOperation(root,"repo_knowledge_register",{knowledge:"docs/architecture.md",sources:["src/**/*.ts"]});assert.equal(result.exitCode,0);result=await invokeOperation(root,"repo_knowledge_verify",{knowledge:"docs/architecture.md",evidence:"reviewed against engine"});assert.equal(result.exitCode,0);const manifestText=await readFile(join(root,".rke","repo-context.json"),"utf8");const manifest=JSON.parse(manifestText) as {knowledge:{verified:Record<string,unknown>}[]};const receipt=manifest.knowledge[0]!.verified;assert.ok(Array.isArray(receipt.sourceIdentities));assert.equal(receipt.sourceHashes,undefined);assert.doesNotMatch(manifestText,/"auth\.ts"\s*:\s*"[a-f0-9]{64}"/);const leakScan=spawnSync("gitleaks",["detect","--no-banner","--no-git","--source",root],{encoding:"utf8",windowsHide:true});if(leakScan.error&&(leakScan.error as NodeJS.ErrnoException).code==="ENOENT")t.diagnostic("gitleaks is unavailable; receipt-shape assertion remains active");else assert.equal(leakScan.status,0,leakScan.stderr||leakScan.stdout);result=await invokeOperation(root,"repo_context_check",{});assert.equal(result.exitCode,0);assert.equal((result.payload.knowledge as Record<string,unknown>).fresh,true);result=await invokeOperation(root,"repo_knowledge_impact",{changedPaths:["src/engine.ts"]});assert.deepEqual(result.payload.affectedKnowledge,["docs/architecture.md"]);await writeFile(join(root,"src","engine.ts"),"export const engine = false;\n");result=await invokeOperation(root,"repo_context_check",{});assert.equal(result.exitCode,3);assert.deepEqual((result.payload.knowledge as Record<string,unknown>).stale,["docs/architecture.md"]);});
test("legacy sourceHashes receipts remain readable during migration",async()=>{const root=await mkdtemp(join(tmpdir(),"rke-legacy-hashes-"));spawnSync("git",["init"],{cwd:root});await mkdir(join(root,"docs"),{recursive:true});await mkdir(join(root,"src"),{recursive:true});await writeFile(join(root,"docs","architecture.md"),"# Architecture\n");await writeFile(join(root,"src","engine.ts"),"export const engine = true;\n");await invokeOperation(root,"repo_knowledge_register",{knowledge:"docs/architecture.md",sources:["src/**/*.ts"]});await invokeOperation(root,"repo_knowledge_verify",{knowledge:"docs/architecture.md",evidence:"migration fixture"});const path=join(root,".rke","repo-context.json");const manifest=JSON.parse(await readFile(path,"utf8")) as {knowledge:{verified:{sourceIdentities:{path:string;sha256:string}[];sourceHashes?:Record<string,string>}}[]};const receipt=manifest.knowledge[0]!.verified;receipt.sourceHashes=Object.fromEntries(receipt.sourceIdentities.map(item=>[item.path,item.sha256]));delete (receipt as {sourceIdentities?:unknown}).sourceIdentities;await writeFile(path,`${JSON.stringify(manifest,null,2)}\n`);const result=await invokeOperation(root,"repo_context_check",{});assert.equal(result.exitCode,0);assert.equal((result.payload.knowledge as Record<string,unknown>).fresh,true);});
test("knowledge validation reports graph connectivity",async()=>{const root=await mkdtemp(join(tmpdir(),"rke-graph-"));await mkdir(join(root,"docs","knowledge"),{recursive:true});const header=(title:string)=>`---\ntype: Architecture Concept\ntitle: ${title}\ndescription: ${title} contract.\n---\n\n# ${title}\n\n`;await writeFile(join(root,"docs","knowledge","a.md"),`${header("A")}See [B](b.md).\n`);await writeFile(join(root,"docs","knowledge","b.md"),`${header("B")}Linked from A.\n`);const result=await invokeOperation(root,"repo_knowledge_bundle_check",{bundle:"docs/knowledge"});assert.equal(result.exitCode,0);assert.equal(result.payload.componentCount,1);assert.deepEqual(result.payload.orphans,[]);});
test("documentation receipts gate closure and become stale with the delta",async()=>{const root=await mkdtemp(join(tmpdir(),"rke-docs-"));spawnSync("git",["init"],{cwd:root});spawnSync("git",["config","user.email","tests@example.test"],{cwd:root});spawnSync("git",["config","user.name","RKE Tests"],{cwd:root});await mkdir(join(root,"docs","knowledge"),{recursive:true});await mkdir(join(root,"src"),{recursive:true});await writeFile(join(root,"src","engine.ts"),"export const mode = 'before';\n");await writeFile(join(root,"docs","knowledge","architecture.md"),"---\ntype: Architecture Concept\ntitle: Runtime mode\ndescription: Explains the runtime mode.\n---\n\n# Runtime mode\n\nThe runtime uses before mode.\n");await invokeOperation(root,"repo_knowledge_register",{knowledge:"docs/knowledge/architecture.md",sources:["src/**/*.ts"]});spawnSync("git",["add","."],{cwd:root});spawnSync("git",["commit","-m","baseline"],{cwd:root});await invokeOperation(root,"workflow_activate",{});await writeFile(join(root,"src","engine.ts"),"export const mode = 'after';\n");await writeFile(join(root,"docs","knowledge","architecture.md"),"---\ntype: Architecture Concept\ntitle: Runtime mode\ndescription: Explains the runtime mode.\n---\n\n# Runtime mode\n\nThe runtime uses after mode.\n");let result=await invokeOperation(root,"workflow_closure_assess",{base:"HEAD"});assert.equal(result.exitCode,3);await mkdir(join(root,".engineering-workflow"),{recursive:true});await writeFile(join(root,".engineering-workflow","change-detail.json"),JSON.stringify({before:"mode was before",after:"mode is after",why:"the accepted runtime mode changed",causalPath:[{path:"src/engine.ts",symbol:"mode"}],verification:[{claim:"source now exports after",kind:"code-only",evidence:"src/engine.ts"}]}));result=await invokeOperation(root,"repo_change_explain",{base:"HEAD",summary:"Changed the runtime and its canonical mode documentation.",detailFile:".engineering-workflow/change-detail.json"});assert.equal(result.exitCode,0);result=await invokeOperation(root,"repo_documentation_apply",{base:"HEAD",bundle:"docs/knowledge",knowledgePaths:["docs/knowledge/architecture.md"],evidence:"Reviewed source and documentation together.",readerQueries:["what runtime mode is used"]});assert.equal(result.exitCode,0);result=await invokeOperation(root,"workflow_closure_assess",{base:"HEAD"});assert.equal(result.exitCode,0);await writeFile(join(root,"src","untracked.ts"),"export const untracked = true;\n");result=await invokeOperation(root,"workflow_closure_assess",{base:"HEAD"});assert.equal(result.exitCode,3);const lanes=result.payload.lanes as Record<string,Record<string,unknown>>;assert.equal(lanes.change?.status,"stale");});
test("documentation bootstrap is read-only and classifies an inherited repository",async()=>{const root=await mkdtemp(join(tmpdir(),"rke-bootstrap-"));await cp(join(process.cwd(),"tests","fixtures","documentation-bootstrap","zero-state"),root,{recursive:true});const result=await invokeOperation(root,"repo_documentation_bootstrap",{});assert.equal(result.exitCode,0);assert.equal(result.payload.startingState,"no-rke");assert.equal(result.payload.outcome,"foundation-required");assert.ok((result.payload.preserve as string[]).includes("README.md"));});
