import assert from "node:assert/strict";
import test from "node:test";
import { mkdir, mkdtemp, stat, symlink, utimes, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { spawnSync } from "node:child_process";

import { repositoryPath } from "../src/paths.js";
import { RepositoryEngine } from "../src/repository-engine.js";
import { invokeOperation } from "../src/operations.js";

test("full content verification detects same-size tracked edits with restored timestamps",async()=>{const root=await mkdtemp(join(tmpdir(),"rke-identity-"));spawnSync("git",["init"],{cwd:root});spawnSync("git",["config","user.email","rke-test@example.invalid"],{cwd:root});spawnSync("git",["config","user.name","RKE Test"],{cwd:root});const path=join(root,"value.ts");await writeFile(path,"export const value = 'alpha';\n");spawnSync("git",["add","value.ts"],{cwd:root});spawnSync("git",["commit","-m","fixture"],{cwd:root});const details=await stat(path);const engine=await RepositoryEngine.open(root);await engine.ensureFresh();await writeFile(path,"export const value = 'bravo';\n");await utimes(path,details.atime,details.mtime);const refresh=await engine.ensureFresh(true);assert.equal(refresh.parsed,1);assert.ok((await engine.search("bravo",5)).length>0);engine.close();});
test("secret-like source is omitted and evicts prior indexed content",async()=>{const root=await mkdtemp(join(tmpdir(),"rke-secret-"));spawnSync("git",["init"],{cwd:root});const path=join(root,"config.ts");await writeFile(path,"export const setting = 'safe';\n");const engine=await RepositoryEngine.open(root);await engine.ensureFresh();await writeFile(path,"export const api_key = '1234567890-secret-value';\n");const refresh=await engine.ensureFresh();assert.equal(refresh.omittedSensitive,1);assert.equal((await engine.fileApi("config.ts")).found,false);engine.close();});
test("non-Git repositories use bounded filesystem discovery",async()=>{const root=await mkdtemp(join(tmpdir(),"rke-nongit-"));await writeFile(join(root,"main.ts"),"export function standalone() {}\n");const engine=await RepositoryEngine.open(root);const refresh=await engine.ensureFresh();assert.equal(refresh.parsed,1);engine.close();});
test("repository paths reject traversal and symlink escapes",async(t)=>{const root=await mkdtemp(join(tmpdir(),"rke-path-"));const outside=await mkdtemp(join(tmpdir(),"rke-outside-"));assert.throws(()=>repositoryPath(root,"../outside"),/outside the repository/);try{await symlink(outside,join(root,"linked"),process.platform==="win32"?"junction":"dir");}catch(error){t.skip(`symlink unavailable: ${String(error)}`);return;}assert.throws(()=>repositoryPath(root,"linked/secret.txt"),/outside the repository/);});
test("source evidence excludes secrets and oversized files from search and review",async()=>{const root=await mkdtemp(join(tmpdir(),"rke-evidence-"));spawnSync("git",["init"],{cwd:root});await writeFile(join(root,"safe.ts"),"export const visible = true;\n");await writeFile(join(root,"config.ts"),"export const api_key = '1234567890-secret-value';\n");await writeFile(join(root,"large.ts"),`export const ${"a".repeat(1_048_576)} = true;\n`);const engine=await RepositoryEngine.open(root);const matches=await engine.findAll("api_key|visible|aaaa",10);assert.deepEqual(matches.map(row=>row.path),["safe.ts"]);await assert.rejects(()=>invokeOperation(root,"repo_prepare_code_review",{path:"config.ts"}),/Sensitive source/);await assert.rejects(()=>invokeOperation(root,"repo_prepare_code_review",{path:"large.ts"}),/evidence boundary/);engine.close();});
test("path traversal and symlink escapes cannot enter review packets",async(t)=>{const root=await mkdtemp(join(tmpdir(),"rke-review-path-"));const outside=await mkdtemp(join(tmpdir(),"rke-review-outside-"));await writeFile(join(outside,"outside.ts"),"export const outside = true;\n");await assert.rejects(()=>invokeOperation(root,"repo_prepare_code_review",{path:"../outside.ts"}),/repository-relative/);try{await symlink(outside,join(root,"linked"),process.platform==="win32"?"junction":"dir");}catch(error){t.skip(`symlink unavailable: ${String(error)}`);return;}await assert.rejects(()=>invokeOperation(root,"repo_prepare_code_review",{path:"linked/outside.ts"}),/outside the repository/);});
test("pathological regex is terminated without locking subsequent queries",async()=>{const root=await mkdtemp(join(tmpdir(),"rke-regex-timeout-"));spawnSync("git",["init"],{cwd:root});await writeFile(join(root,"main.ts"),`${"a".repeat(20_000)}b\nexport const healthy = true;\n`);const engine=await RepositoryEngine.open(root);await assert.rejects(()=>engine.findAll("^(a+)+$",10),/five-second per-file limit/);assert.ok((await engine.findAll("healthy",10)).length>0);engine.close();});
test("agent review is digest-bound and contributes to file, trace and impact evidence",async()=>{const root=await mkdtemp(join(tmpdir(),"rke-reviewed-"));spawnSync("git",["init"],{cwd:root});await writeFile(join(root,"legacy.vb"),"Function Legacy()\n    Return Helper()\nEnd Function\n");const engine=await RepositoryEngine.open(root);const before=await engine.fileApi("legacy.vb");assert.equal(before.analysisMode,"agent-review-required");const packet=await invokeOperation(root,"repo_prepare_code_review",{path:"legacy.vb"});const review={sourceDigest:packet.payload.digest,symbols:[{name:"Legacy",qualname:"Legacy",kind:"function",signature:"Function Legacy()",startLine:1,endLine:3,confidence:"medium"}],imports:[],calls:[{source:"Legacy",target:"Helper",kind:"call",confidence:"medium"}],diagnostics:[]};await invokeOperation(root,"repo_record_code_review",{path:"legacy.vb",review});const file=await engine.fileApi("legacy.vb");assert.equal(file.analysisMode,"agent-reviewed");assert.match(JSON.stringify(await engine.trace("Legacy","callees")),/Helper/);assert.match(JSON.stringify(await engine.changeImpact(["legacy.vb"])),/Legacy/);await writeFile(join(root,"legacy.vb"),"Function Legacy()\n    Return Different()\nEnd Function\n");assert.equal((await engine.fileApi("legacy.vb")).analysisMode,"agent-review-required");assert.doesNotMatch(JSON.stringify(await engine.trace("Legacy","callees")),/Helper/);await assert.rejects(()=>invokeOperation(root,"repo_record_code_review",{path:"legacy.vb",review}),/sourceDigest/);engine.close();});
test("local workflow cache cannot be returned as source evidence",async()=>{const root=await mkdtemp(join(tmpdir(),"rke-local-cache-"));await mkdir(join(root,".engineering-workflow"));await writeFile(join(root,".engineering-workflow","state.json"),"{\"private\":true}\n");await assert.rejects(()=>invokeOperation(root,"repo_prepare_code_review",{path:".engineering-workflow/state.json"}),/excluded/);});
test("review packet truncates a long in-bound line",async()=>{const root=await mkdtemp(join(tmpdir(),"rke-review-line-"));await writeFile(join(root,"long.ts"),"x".repeat(10_000));const prepared=await invokeOperation(root,"repo_prepare_code_review",{path:"long.ts"});assert.equal(prepared.payload.truncated,true);const slices=prepared.payload.slices as {numberedSource:string}[];assert.ok(slices[0]!.numberedSource.length<1100);});
