import assert from "node:assert/strict";
import { mkdtemp, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { isAbsolute, join, resolve } from "node:path";
import { spawnSync } from "node:child_process";
import { VERSION } from "../src/version.js";

const supplied=process.argv[2];
if(!supplied)throw new Error("Usage: smoke-distribution <npm-tarball>");
const tarball=isAbsolute(supplied)?supplied:resolve(supplied);
const root=await mkdtemp(join(tmpdir(),"rke-package-smoke-"));
const npmCli=process.env.npm_execpath;
const installArgs=["install","--ignore-scripts","--prefix",root,tarball];
const installed=npmCli?spawnSync(process.execPath,[npmCli,...installArgs],{cwd:root,encoding:"utf8",windowsHide:true}):spawnSync("npm",installArgs,{cwd:root,encoding:"utf8",windowsHide:true});
assert.equal(installed.status,0,installed.error?.message||installed.stderr||installed.stdout);
const cli=join(root,"node_modules","@polaralias","rke","dist","src","cli.js"),mcp=join(root,"node_modules","@polaralias","rke","dist","src","mcp.js"),evaluator=join(root,"node_modules","@polaralias","rke","dist","src","evaluate-agent.js");
const version=spawnSync(process.execPath,[cli,"--version"],{cwd:root,encoding:"utf8",windowsHide:true});
assert.equal(version.status,0,version.stderr);assert.equal(version.stdout.trim(),VERSION);
await writeFile(join(root,"service.ts"),"export function packagedRuntime() { return 1; }\n");
const retrieval=spawnSync(process.execPath,[cli,"context","find","packaged runtime","--root",root],{cwd:root,encoding:"utf8",windowsHide:true});
assert.equal(retrieval.status,0,retrieval.stderr||retrieval.stdout);assert.match(retrieval.stdout,/service\.ts/);
const request=JSON.stringify({jsonrpc:"2.0",id:1,method:"initialize",params:{protocolVersion:"2025-11-25",capabilities:{},clientInfo:{name:"smoke",version:"1"}}})+"\n"+JSON.stringify({jsonrpc:"2.0",id:2,method:"tools/list",params:{}})+"\n";
const transport=spawnSync(process.execPath,[mcp,"--root",root],{cwd:root,input:request,encoding:"utf8",windowsHide:true});
assert.equal(transport.status,0,transport.stderr);assert.match(transport.stdout,/repo_find_context/);
const evaluation=spawnSync(process.execPath,[evaluator,"--list"],{cwd:root,encoding:"utf8",windowsHide:true});
assert.equal(evaluation.status,0,evaluation.stderr);assert.equal((JSON.parse(evaluation.stdout) as {caseCount:number}).caseCount,6);
console.log(`Clean npm artefact smoke passed at ${root}: version, parser retrieval, MCP tool discovery, and evaluator corpus.`);
