#!/usr/bin/env node
import { realpathSync, statSync } from "node:fs";
import { relative, resolve, sep } from "node:path";
import { createInterface } from "node:readline";

import { asError, RkeError } from "./errors.js";
import { git } from "./io.js";
import { invokeOperation, OPERATIONS } from "./operations.js";
import { VERSION } from "./version.js";

const LEGACY_PROTOCOL="2025-11-25", MODERN_PROTOCOL="2026-07-28", MAX_MESSAGE_BYTES=4*1024*1024;
const SERVER_INFO={name:"rke",version:VERSION};
const argv=process.argv.slice(2);let fixedRoot:string|undefined;const allowedRoots:string[]=[];
for(let index=0;index<argv.length;index++){if(argv[index]==="--root")fixedRoot=realpathSync.native(resolve(argv[++index]??""));else if(argv[index]==="--allow-root")allowedRoots.push(realpathSync.native(resolve(argv[++index]??"")));else throw new Error(`Unknown argument: ${argv[index]}`);}

interface Request { jsonrpc?:string; id?:unknown; method?:string; params?:Record<string,unknown> }
function envelope(id:unknown,result?:unknown,error?:unknown):Record<string,unknown>{return error?{jsonrpc:"2.0",id,error}:{jsonrpc:"2.0",id,result};}
function emit(value:Record<string,unknown>):void{process.stdout.write(`${JSON.stringify(value)}\n`);}
function modern(request:Request):boolean{const meta=request.params?._meta;return !!meta&&typeof meta==="object"&&(meta as Record<string,unknown>)["io.modelcontextprotocol/protocolVersion"]===MODERN_PROTOCOL;}
function modernResult(payload:Record<string,unknown>,cacheable=false):Record<string,unknown>{return{...payload,resultType:"complete",_meta:{"io.modelcontextprotocol/serverInfo":SERVER_INFO},...(cacheable?{ttlMs:0,cacheScope:"private"}:{})};}
function toolDefinitions(repositoryRequired:boolean):Record<string,unknown>[]{return OPERATIONS.map(operation=>{const inputSchema=structuredClone(operation.inputSchema) as Record<string,unknown>;if(repositoryRequired){const properties=inputSchema.properties as Record<string,unknown>;properties.repository={type:"string",description:"Absolute path to the Git repository for this operation."};inputSchema.required=[...new Set([...(inputSchema.required as string[]??[]),"repository"])];}return{name:operation.name,title:operation.title,description:operation.description,inputSchema,annotations:{readOnlyHint:operation.readOnly,idempotentHint:operation.idempotent}};});}
function within(path:string,boundary:string):boolean{const rel=relative(boundary,path);return rel===""||(!rel.startsWith(`..${sep}`)&&rel!==".."&&!rel.startsWith("/"));}
function repository(argumentsValue:unknown):{root:string,args:Record<string,unknown>}{if(!argumentsValue||typeof argumentsValue!=="object"||Array.isArray(argumentsValue))throw new RkeError("invalid_operation_arguments","Operation arguments must be an object.");const args={...argumentsValue as Record<string,unknown>};const requested=args.repository;delete args.repository;let root:string;if(fixedRoot){root=fixedRoot;if(requested!==undefined&&realpathSync.native(resolve(String(requested)))!==root)throw new RkeError("repository_boundary_violation","This compatibility server is fixed to a different repository.");}else{if(typeof requested!=="string"||!requested.trim())throw new RkeError("repository_required","Argument 'repository' must identify a Git repository.");root=realpathSync.native(resolve(requested));if(!statSync(root).isDirectory())throw new RkeError("repository_missing",`Repository directory does not exist: ${root}`);if(git(root,"rev-parse","--show-toplevel").code!==0)throw new RkeError("git_repository_required",`Path is not inside a Git repository: ${root}`);}if(allowedRoots.length&&!allowedRoots.some(boundary=>within(root,boundary)))throw new RkeError("repository_not_allowed",`Repository is outside the configured allowed roots: ${root}`);return{root,args};}

async function dispatch(request:Request):Promise<Record<string,unknown>|null>{const id=request.id;if(request.jsonrpc!=="2.0"||typeof request.method!=="string")return envelope(id,undefined,{code:-32600,message:"Invalid Request"});if(!("id" in request))return null;const isModern=modern(request);const meta=request.params?._meta as Record<string,unknown>|undefined;const version=meta?.["io.modelcontextprotocol/protocolVersion"];if(request.method==="server/discover"||version!==undefined){if(version!==MODERN_PROTOCOL)return envelope(id,undefined,{code:-32022,message:"Unsupported protocol version",data:{supported:[MODERN_PROTOCOL,LEGACY_PROTOCOL],requested:version}});if(!meta?.["io.modelcontextprotocol/clientCapabilities"]||typeof meta["io.modelcontextprotocol/clientCapabilities"]!=="object")return envelope(id,undefined,{code:-32602,message:"Modern requests require client capabilities in params._meta."});}
  if(request.method==="server/discover")return envelope(id,modernResult({supportedVersions:[MODERN_PROTOCOL,LEGACY_PROTOCOL],capabilities:{tools:{}},instructions:"Use shared engineering operations for bounded repository evidence and governed maintenance."},true));
  if(request.method==="initialize")return envelope(id,{protocolVersion:LEGACY_PROTOCOL,capabilities:{tools:{}},serverInfo:SERVER_INFO});
  if(request.method==="ping")return envelope(id,isModern?modernResult({}):{});
  if(request.method==="tools/list"){const payload={tools:toolDefinitions(!fixedRoot)};return envelope(id,isModern?modernResult(payload,true):payload);}
  if(request.method!=="tools/call")return envelope(id,undefined,{code:-32601,message:"Method not found"});
  if(!request.params||typeof request.params.name!=="string")return envelope(id,undefined,{code:-32602,message:"Invalid tools/call parameters"});
  try{const selected=repository(request.params.arguments??{});const outcome=await invokeOperation(selected.root,request.params.name,selected.args);const result={content:[{type:"text",text:JSON.stringify(outcome.payload)}],structuredContent:outcome.payload,isError:outcome.exitCode!==0};return envelope(id,isModern?modernResult(result):result);}catch(error){if(error instanceof RkeError){const result={content:[{type:"text",text:JSON.stringify({code:error.code,message:error.message})}],structuredContent:{code:error.code,message:error.message},isError:true};return envelope(id,isModern?modernResult(result):result);}const value=asError(error);process.stderr.write(`rke-mcp internal tool failure: ${value.name}\n`);const result={content:[{type:"text",text:JSON.stringify({code:"internal_operation_error",message:"The operation failed unexpectedly; the MCP server remains available."})}],isError:true};return envelope(id,isModern?modernResult(result):result);}}

async function processLine(line:string):Promise<void>{if(Buffer.byteLength(line,"utf8")>MAX_MESSAGE_BYTES){emit(envelope(null,undefined,{code:-32600,message:"Message exceeds maximum size"}));return;}let request:Request;try{request=JSON.parse(line) as Request;}catch{emit(envelope(null,undefined,{code:-32700,message:"Parse error"}));return;}const response=await dispatch(request);if(response)emit(response);}
const lines=createInterface({input:process.stdin,crlfDelay:Infinity});let queue=Promise.resolve();lines.on("line",line=>{queue=queue.then(()=>processLine(line)).catch(error=>emit(envelope(null,undefined,{code:-32603,message:asError(error).message})));});
